FROM ubuntu:24.10

RUN apt-get update && \
    apt-get install -y --no-install-recommends wget tar ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://download.java.net/openjdk/jdk22/ri/openjdk-22+36_linux-x64_bin.tar.gz && \
    mkdir -p /usr/local/java && \
    tar -xvzf openjdk-22+36_linux-x64_bin.tar.gz -C /usr/local/java && \
    rm openjdk-22+36_linux-x64_bin.tar.gz

RUN ln -s /usr/local/java/jdk-22/bin/java /usr/bin/java && \
    ln -s /usr/local/java/jdk-22/bin/javac /usr/bin/javac
